### PR TITLE
Prepared package to add to ckeditor5 repository

### PR DESCRIPTION
**Pull request by pomek**
Other: Prepared package to add to [`ckeditor/ckeditor5`](https://github.com/ckeditor/ckeditor5) repository. See ckeditor/ckeditor5#924.

### CODE REVIEW

**Comment by czerwonkabartosz** [comment]
For me, it's ok ;)

**Comment by pomek** [comment]
image

:(

**Comment by ma2ciek** [comment]
@pomek, do you remember at which point this task was abandoned? At the https://github.com/cksource/mgit2/pull/98?

**Comment by pomek** [comment]
It was never abandoned. It just waits for reviews all related things…

**Comment by ma2ciek** [comment]
@pomek, Could you resolve conflicts?

**Comment by pomek** [comment]
Resolved but now we need to learn our CI-dev-tool how to handle mgit's `"overrideDirectoryNames"` option…

**Comment by ma2ciek** [comment]
> Resolved but now we need to learn our CI-dev-tool how to handle mgit's "overrideDirectoryNames" option…

Could you prepare the ticket for it? So we'll move forward.

**Pull request merged**
